#include "main.h"
#include <mrc_base.h>
#include <mrc_exb.h>
#include <mrc_jgraphics.h>
#include <mrc_win.h>
#include <mrc_text.h>
#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 320
#define SCREEN_WIDTH2 260
#define SCREEN_HEIGHT2 290
#define SCREEN_WIDTH2F 130.0f
#define SCREEN_HEIGHT2F 140.0f
#define WORLD_SX 16
#define WORLD_SY 8
#define WORLD_SZ 16
#define HALFPI 1.57079637f
#define PI 3.14159265f
#define TWO_PI 6.283185307f
#define FOCAL_LENGTH 200.0f
#define NEAR_Z 0.5f
#define SIN_LUT_SIZE 256
#define SIN_LUT_SIZEF 256.0F
static float sin_lut[SIN_LUT_SIZE];

/* ===== Q16.16 fixed-point math =================================== */
typedef int32 fx32;

/* The MTK / MRE SDK headers don't always typedef a 64-bit type, but
   the underlying ARM toolchain (RVCT / armcc / gcc) supports it as
   `long long`.  We need it for the multiply / divide intermediates. */
#ifndef MRE_HAS_INT64
typedef long long int64;
typedef unsigned long long uint64;
#define MRE_HAS_INT64 1
#endif

#define FX_SHIFT          16
#define FX_ONE            ((fx32)0x00010000)             /* 65536 */
#define FX_HALF           ((fx32)0x00008000)             /* 32768 */
#define FX_FROM_INT(i)    ((fx32)((int32)(i) << FX_SHIFT))
#define FX_TO_INT(f)      ((int32)((f) >> FX_SHIFT))
#define FX_FROM_FLOAT(f)  ((fx32)((float)(f) * 65536.0f))
#define FX_TO_FLOAT(f)    ((float)(f) * (1.0f / 65536.0f))

/* (a * b) >> 16 with 64-bit intermediate to avoid overflow.
   ARM926 has no native 64-bit multiply, but the compiler emits a
   reasonable __aeabi_lmul, which is still ~10x cheaper than a
   software-float multiply on a no-FPU core. */
#define FX_MUL(a, b) ((fx32)((((int64)(a)) * ((int64)(b))) >> FX_SHIFT))

/* (a << 16) / b, again with 64-bit intermediate. */
#define FX_DIV(a, b) ((fx32)((((int64)(a)) << FX_SHIFT) / (int64)(b)))

#define FX_NEAR_Z      ((fx32)(FX_HALF))                 /* 0.5 */
#define FX_FOCAL       ((fx32)(200 * FX_ONE))            /* 200.0 */
#define FX_SCREEN_HW   ((fx32)(130 * FX_ONE))            /* 130.0 */
#define FX_SCREEN_HH   ((fx32)(140 * FX_ONE))            /* 140.0 */

/* Q16.16 sine LUT, 1024 entries.  Index = (angle * 1024 / TWO_PI) mod 1024.
   Generated by gen_sin_LUT.py (with TABLE_SIZE = 1024). */
#define FX_SIN_LUT_SIZE 1024
#define FX_SIN_LUT_MASK 1023
extern const int32 fx_sin_lut[FX_SIN_LUT_SIZE];  /* defined at end of file */

/* (1024 / 2*PI) in Q16.16 for the angle->index conversion. */
#define FX_LUT_SCALE   ((fx32)10680707)  /* (1024 / (2*PI)) * 65536 */
/* PI/2 in Q16.16. */
#define FX_HALFPI      ((fx32)102944)

__inline fx32 fx_sin(fx32 angle_fx) {
    /* Convert fx-radians to LUT index, wrap with bitmask. */
    int32 idx = FX_MUL(angle_fx, FX_LUT_SCALE) >> FX_SHIFT;
    return fx_sin_lut[idx & FX_SIN_LUT_MASK];
}
__inline fx32 fx_cos(fx32 angle_fx) {
    return fx_sin(angle_fx + FX_HALFPI);
}
/* ================================================================== */

uint8 world[WORLD_SX][WORLD_SY][WORLD_SZ];
uint8 visibleFaces[WORLD_SX][WORLD_SY][WORLD_SZ];

/* Face index -> neighbour offset.
   Order matches `faces[6][4]` in drawCube:
     0 = -Z, 1 = +Z, 2 = -Y, 3 = +Y, 4 = -X, 5 = +X */
static const int8 face_dx[6] = {  0,  0,  0,  0, -1,  1 };
static const int8 face_dy[6] = {  0,  0, -1,  1,  0,  0 };
static const int8 face_dz[6] = { -1,  1,  0,  0,  0,  0 };
mrc_jgraphics_context_t *gContext; 
Camera cam;
/* 3D world position of the Mario billboard. y=1.5 puts him on top of
   the grass surface (grass index = WORLD_SY-5 = 3, top of that block
   at world Y=2.0). Z=4 places him a few blocks in front of the camera. */
Vec3 marioPos = { 8.0f, 1.5f, 4.0f };
/* ---- Animation / FPS / raycast-action globals ----
   g_frame_count    -- monotonically incremented each mrc_draw, drives Mario
                       walk animation (sin sweep around marioPos.x).
   g_fps            -- frames-per-second computed over the most recent
                       ~1s window via mr_getTime().
   g_action_break / g_action_place
                    -- one-shot flags set by mrc_event when the user hits
                       '5' (break) or '0' (place); consumed by the next
                       mrc_draw via castRayAndAct(). */
int   g_frame_count        = 0;
int   g_fps                = 0;
int32 g_fps_window_start_ms = 0;
int   g_fps_window_frames  = 0;
int   g_fps_inited         = 0;
int   g_action_break       = 0;
int   g_action_place       = 0;
/* Mario walk-cycle parameters. */
#define MARIO_ANIM_SPEED   0.10f   /* radians per frame */
#define MARIO_ANIM_RANGE   1.5f    /* world-units swing in +/-X */
/* Player reach for break / place. */
#define PLAYER_REACH       6.0f
#define RAY_STEP           0.10f
CBitmap handBmp;
CBitmap GUIBmp;
CBitmap marioBmp;
int g_curr_tx = 120;
int g_curr_ty = 160;
int diff_x = 0;
int diff_y = 0;
float dx = 0;
float dz = 0;
float move_speed = 1.0f;
float rot_speed = 0.0004f;
int globalTimer;


float my_fmodf(float x, float y) {
    if (y == 0) return 0;
    return x - (float)((int)(x / y)) * y; 
}

/* sin(x) via the first 5 Taylor-series terms (degrees up to x^9).
   The original code dropped the iterative `term *= ...` step and so was
   wildly wrong for |x| > ~1 -- because the sin LUT is computed from
   this function once at startup, that bug poisoned every later call to
   my_sinf() with garbage values. */
float my_sinf_legacy(float x) {
    float res, angle, xopt, term;
    int i;
    angle = my_fmodf(x, TWO_PI);
    if (angle > PI) angle -= TWO_PI;
    else if (angle < -PI) angle += TWO_PI;
    res = angle;
    term = angle;
    xopt = -angle * angle;
    for (i = 1; i <= 4; i++) {
        term *= xopt / ((2.0f * i) * (2.0f * i + 1.0f));
        res += term;
    }
    return res;
}

void initSinLUT(void) {
    int i;
    float angle;
    for (i = 0; i < SIN_LUT_SIZE; i++) {
        angle = ((float)i / (float)SIN_LUT_SIZE) * TWO_PI;
        sin_lut[i] = (float)my_sinf_legacy(angle); 
    }
}

__inline void initSprite(CBitmap* bmp, int w, int h, unsigned char* pixels)
{
	bmp->width = w;
	bmp->height = h;
	bmp->pixels = pixels;
}

void initSpriteData(void)
{
	initSprite(&handBmp, 64, 64, (unsigned char*)_sprHand);
    initSprite(&GUIBmp, 240, 64, (unsigned char*)_sprGUIPH);
    initSprite(&marioBmp, 16, 16, (unsigned char*)_sprMario);
}

float my_sinf(float x) {
    int index;
    float phase;
    phase = x;
    while (phase < 0) phase += TWO_PI;
    while (phase >= TWO_PI) phase -= TWO_PI;
    index = (int)((phase / TWO_PI) * SIN_LUT_SIZEF);
    return sin_lut[index];
}

float my_cosf(float x) {
    return my_sinf(x + HALFPI);
}

void gDrawBitmap(CBitmap* bmp, int x, int y)
{
	mrc_bitmapShowEx((uint16*)bmp->pixels, x, y, bmp->width, bmp->width, bmp->height, BM_TRANSPARENT, 0, 0);
}
void gDrawBitmapNt(CBitmap* bmp, int x, int y)
{
	mrc_bitmapShowEx((uint16*)bmp->pixels, x, y, bmp->width, bmp->width, bmp->height, BM_COPY, 0, 0);
}

/* Nearest-neighbor scaled blit of an RGB565 sprite to (dst_x..+dst_w,
   dst_y..+dst_h). 0x0000 in the source is treated as transparent. Output is
   produced as run-length horizontal lines via mrc_drawLine, so contiguous
   same-color spans cost just one line draw each (cheap on MRE). */
void gDrawBitmap3DScaled(CBitmap* bmp, int dst_x, int dst_y, int dst_w, int dst_h)
{
    uint16* pixels;
    int sw, sh;
    int row, col, src_y, src_x, y, x_at_col;
    int run_start, x0, x1;
    uint16 px, run_color;
    uint8 r, g, b;
    int flush;

    if (bmp == NULL || dst_w <= 0 || dst_h <= 0) return;
    pixels = (uint16*)bmp->pixels;
    sw = bmp->width;
    sh = bmp->height;

    for (row = 0; row < dst_h; row++) {
        y = dst_y + row;
        if (y < 0 || y >= SCREEN_HEIGHT) continue;
        src_y = (row * sh) / dst_h;
        run_start = -1;
        run_color = 0;
        for (col = 0; col <= dst_w; col++) {
            x_at_col = dst_x + col;
            if (col < dst_w) {
                src_x = (col * sw) / dst_w;
                px = pixels[src_y * sw + src_x];
            } else {
                px = 0; /* sentinel flushes any open run */
            }
            flush = 0;
            if (run_start >= 0) {
                if (col >= dst_w || px != run_color ||
                    x_at_col < 0 || x_at_col >= SCREEN_WIDTH) {
                    flush = 1;
                }
            }
            if (flush) {
                x0 = dst_x + run_start;
                x1 = x_at_col - 1;
                if (x0 < 0) x0 = 0;
                if (x1 >= SCREEN_WIDTH) x1 = SCREEN_WIDTH - 1;
                if (x1 >= x0) {
                    r = (uint8)(((run_color >> 11) & 0x1F) << 3);
                    g = (uint8)(((run_color >>  5) & 0x3F) << 2);
                    b = (uint8)((run_color & 0x1F) << 3);
                    mrc_drawLine((int16)x0, (int16)y, (int16)x1, (int16)y,
                                 r, g, b);
                }
                run_start = -1;
            }
            if (run_start < 0 && col < dst_w &&
                px != 0x0000 && x_at_col >= 0 && x_at_col < SCREEN_WIDTH) {
                run_start = col;
                run_color = px;
            }
        }
    }
}

/* Project a world point and draw `bmp` as a perspective-scaled billboard
   centered on it. sprite_world_h_fx is the desired sprite height in world
   units (Q16.16); on-screen size becomes sprite_world_h_fx * FOCAL/final_z.
   Returns silently if Mario is behind the near plane or fully off-screen. */
void drawSprite3D_fx(CBitmap* bmp,
                     fx32 wx, fx32 wy, fx32 wz, fx32 sprite_world_h_fx,
                     fx32 cosY_fx, fx32 sinY_fx,
                     fx32 cosP_fx, fx32 sinP_fx,
                     fx32 cam_x_fx, fx32 cam_y_fx, fx32 cam_z_fx)
{
    fx32 dxw, dyw, dzw, rx, rz;
    fx32 final_x, final_y, final_z, invZ, screen_size_fx;
    int16 sx, sy;
    int dst_size, half;

    dxw = wx - cam_x_fx;
    dyw = wy - cam_y_fx;
    dzw = wz - cam_z_fx;
    rx = FX_MUL(dxw, cosY_fx) + FX_MUL(dzw, sinY_fx);
    rz = -FX_MUL(dxw, sinY_fx) + FX_MUL(dzw, cosY_fx);
    final_x = rx;
    final_y = FX_MUL(dyw, cosP_fx) - FX_MUL(rz, sinP_fx);
    final_z = FX_MUL(dyw, sinP_fx) + FX_MUL(rz, cosP_fx);

    if (final_z < FX_NEAR_Z) return;
    invZ = FX_DIV(FX_FOCAL, final_z);
    sx = (int16)FX_TO_INT(FX_MUL(final_x, invZ) + FX_SCREEN_HW);
    sy = (int16)FX_TO_INT(FX_MUL(final_y, invZ) + FX_SCREEN_HH);

    screen_size_fx = FX_MUL(sprite_world_h_fx, invZ);
    dst_size = FX_TO_INT(screen_size_fx);
    if (dst_size < 2) return;
    if (dst_size > SCREEN_HEIGHT) dst_size = SCREEN_HEIGHT;

    half = dst_size >> 1;
    if (sx + half < 0 || sx - half >= SCREEN_WIDTH) return;
    if (sy + half < 0 || sy - half >= SCREEN_HEIGHT) return;

    gDrawBitmap3DScaled(bmp, sx - half, sy - half, dst_size, dst_size);
}

int32 mrc_extRecvAppEvent(int32 app, int32 code, int32 param0, int32 param1)
{
        return MR_SUCCESS;
}
int32 mrc_extRecvAppEventEx(int32 code, int32 p0, int32 p1, int32 p2, int32 p3, int32 p4,int32 p5)
{
        return MR_SUCCESS;
}


int32 mrc_pause(void)
{
	return MR_SUCCESS;
}

void reverse(char s[]) {
    int i, j;
    char c;
    for (i = 0, j = strlen(s)-1; i<j; i++, j--) {
        c = s[i];
        s[i] = s[j];
        s[j] = c;
    }
}

void int_to_string(int n, char s[]) {
    int i = 0, sign;
    if ((sign = n) < 0) n = -n;
    
    do { 
        s[i++] = n % 10 + '0';
    } while ((n /= 10) > 0);
    
    if (sign < 0) s[i++] = '-';
    s[i] = '\0';
    reverse(s);
}

int32 mrc_resume(void)
{
	return MR_SUCCESS;
}


int32 mrc_exitApp(void)
{
	
	return MR_SUCCESS;
}
int32 projectPoint(Vec3 world_pt, const Camera *cam, float cosY, float sinY, float cosP, float sinP, int16 *sx, int16 *sy, int16 *sz) {
    float x = world_pt.x - cam->pos.x;
    float y = world_pt.y - cam->pos.y;
    float z = world_pt.z - cam->pos.z;
    float rx = x * cosY + z * sinY;
    float rz = -x * sinY + z * cosY;
    float final_x = rx;
    float final_y = y * cosP - rz * sinP;
    float final_z = y * sinP + rz * cosP;
    float invZ;

    if (final_z < NEAR_Z) {
        return MR_FAILED;
    }

    *sz = (int16)final_z;
    invZ = FOCAL_LENGTH / final_z;

    *sx = (int16)(final_x * invZ + SCREEN_WIDTH2F);
    *sy = (int16)(final_y * invZ + SCREEN_HEIGHT2F);

    return MR_SUCCESS;
}

/* Same projection as projectPoint(), but the inputs are pre-converted Q16.16
   fixed-point values.  Does no software-float work, which is the main hot
   loop on no-FPU ARM926EJ-S cores. */
int32 projectPoint_fx(fx32 wx, fx32 wy, fx32 wz,
                      fx32 cam_x, fx32 cam_y, fx32 cam_z,
                      fx32 cosY, fx32 sinY, fx32 cosP, fx32 sinP,
                      int16 *sx, int16 *sy, int16 *sz) {
    fx32 x  = wx - cam_x;
    fx32 y  = wy - cam_y;
    fx32 z  = wz - cam_z;
    fx32 rx = FX_MUL(x, cosY) + FX_MUL(z, sinY);
    fx32 rz = -FX_MUL(x, sinY) + FX_MUL(z, cosY);
    fx32 final_x = rx;
    fx32 final_y = FX_MUL(y, cosP) - FX_MUL(rz, sinP);
    fx32 final_z = FX_MUL(y, sinP) + FX_MUL(rz, cosP);
    fx32 invZ;

    if (final_z < FX_NEAR_Z) {
        return MR_FAILED;
    }

    /* sz: integer depth, just used for ordering / debugging. */
    *sz = (int16)FX_TO_INT(final_z);

    /* invZ = FX_FOCAL / final_z, also Q16.16. */
    invZ = FX_DIV(FX_FOCAL, final_z);

    /* screen_x = final_x * invZ + half_width.  Result is Q16.16, then
       integer-truncated for an int16 pixel coordinate. */
    *sx = (int16)FX_TO_INT(FX_MUL(final_x, invZ) + FX_SCREEN_HW);
    *sy = (int16)FX_TO_INT(FX_MUL(final_y, invZ) + FX_SCREEN_HH);

    return MR_SUCCESS;
}

/* ===== Tiny 3x5 bitmap font (digits + 'F','P','S',':',' ') =====
   Each row is 3 bits stored in the low nibble; row 0 is the top.
   We only need the chars used by the FPS HUD so the table is small. */
static const uint8 _font3x5[16][5] = {
    /* 0 */ { 0x7,0x5,0x5,0x5,0x7 },
    /* 1 */ { 0x2,0x6,0x2,0x2,0x7 },
    /* 2 */ { 0x6,0x1,0x2,0x4,0x7 },
    /* 3 */ { 0x6,0x1,0x2,0x1,0x6 },
    /* 4 */ { 0x5,0x5,0x7,0x1,0x1 },
    /* 5 */ { 0x7,0x4,0x6,0x1,0x6 },
    /* 6 */ { 0x3,0x4,0x6,0x5,0x2 },
    /* 7 */ { 0x7,0x1,0x2,0x4,0x4 },
    /* 8 */ { 0x2,0x5,0x2,0x5,0x2 },
    /* 9 */ { 0x2,0x5,0x3,0x1,0x6 },
    /* F */ { 0x7,0x4,0x6,0x4,0x4 },
    /* P */ { 0x6,0x5,0x6,0x4,0x4 },
    /* S */ { 0x3,0x4,0x2,0x1,0x6 },
    /* : */ { 0x0,0x2,0x0,0x2,0x0 },
    /* (sp)*/{ 0x0,0x0,0x0,0x0,0x0 },
    /* . */ { 0x0,0x0,0x0,0x0,0x2 }
};
/* Map a logical char to a glyph index in _font3x5. */
static int _font_glyph_index(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c == 'F') return 10;
    if (c == 'P') return 11;
    if (c == 'S') return 12;
    if (c == ':') return 13;
    if (c == '.') return 15;
    return 14; /* space / unknown */
}
/* Draw one 3x5 glyph at (x,y) scaled by `scale` (1 = 3x5 px,
   2 = 6x10, etc). Pixels are emitted as horizontal mrc_drawLine
   runs of width `scale` so a scale=2 char is just 5 line draws. */
static void drawGlyph5(int x, int y, int glyph, int scale,
                       uint8 r, uint8 g, uint8 b)
{
    int row, col, dy, px_x, px_y;
    if (glyph < 0 || glyph >= 16 || scale <= 0) return;
    for (row = 0; row < 5; row++) {
        uint8 bits = _font3x5[glyph][row];
        for (col = 0; col < 3; col++) {
            if (bits & (1 << (2 - col))) {
                px_x = x + col * scale;
                px_y = y + row * scale;
                for (dy = 0; dy < scale; dy++) {
                    mrc_drawLine((int16)px_x, (int16)(px_y + dy),
                                 (int16)(px_x + scale - 1), (int16)(px_y + dy),
                                 r, g, b);
                }
            }
        }
    }
}
/* Draw a NUL-terminated ASCII string left-to-right at (x,y). Each
   char is 3*scale wide with a 1*scale gap, total advance = 4*scale. */
static void drawString5(int x, int y, const char *s, int scale,
                        uint8 r, uint8 g, uint8 b)
{
    int cx = x;
    while (*s) {
        drawGlyph5(cx, y, _font_glyph_index(*s), scale, r, g, b);
        cx += 4 * scale;
        s++;
    }
}
/* Timer tick period -- must match mrc_timerStart() in mrc_init().
   Used by the FPS counter's tick-based fallback when mr_getTime()
   does not advance (some MAUI builds stub it to 0). */
#define FRAME_TICK_MS 33
/* mr_getTime() returns elapsed milliseconds since app start (MRE SDK).
   The SDL2 test harness implements its own version. */
extern int32 mr_getTime(void);
/* Update + draw the FPS counter at top-left.
   Two-source clock: wall-clock from mr_getTime() if it advances,
   otherwise fall back to a synthetic clock built from the timer
   tick rate (FRAME_TICK_MS per call). The fallback always works
   even on platforms where mr_getTime() returns 0/static. */
void drawFpsHud(void)
{
    char buf[16];
    int n;
    int32 now = mr_getTime();
    int elapsed;
    g_fps_window_frames++;
    if (!g_fps_inited) {
        g_fps_window_start_ms = now;
        g_fps_window_frames = 0;
        g_fps_inited = 1;
    }
    elapsed = (int)(now - g_fps_window_start_ms);
    /* If the wall clock is not advancing (mr_getTime stuck at 0),
       synthesise it from the tick count so the HUD still updates. */
    if (elapsed <= 0)
        elapsed = g_fps_window_frames * FRAME_TICK_MS;
    if (elapsed >= 1000) {
        g_fps = (g_fps_window_frames * 1000) / elapsed;
        g_fps_window_start_ms = now;
        g_fps_window_frames = 0;
    }
    /* Build "FPS:NN" or "FPS:NNN" inline (no sprintf to keep MRE
       happy on devices without full libc). */
    buf[0] = 'F'; buf[1] = 'P'; buf[2] = 'S'; buf[3] = ':';
    n = g_fps;
    if (n < 0) n = 0;
    if (n > 999) n = 999;
    if (n >= 100) {
        buf[4] = (char)('0' + (n / 100));
        buf[5] = (char)('0' + ((n / 10) % 10));
        buf[6] = (char)('0' + (n % 10));
        buf[7] = '\0';
    } else if (n >= 10) {
        buf[4] = (char)('0' + (n / 10));
        buf[5] = (char)('0' + (n % 10));
        buf[6] = '\0';
    } else {
        buf[4] = (char)('0' + n);
        buf[5] = '\0';
    }
    /* Drop a 1-px black drop-shadow then bright yellow text. */
    drawString5(5, 5, buf, 2,   0,   0,   0);
    drawString5(4, 4, buf, 2, 255, 220,  40);
}
/* ===== Raycast block break / place =====
   Step a ray from cam.pos along the look direction in small fixed
   increments until either we hit a solid block or run past PLAYER_REACH.
   On hit:
     action == 0 (break): set the hit cell to AIR
     action == 1 (place): set the LAST AIR cell on the ray to DIRT
   In both cases we incrementally rebuild the affected face masks
   via updateFaceMaskRegion(). */
void castRayAndAct(int action)
{
    /* Direction matches the engine's yaw/pitch convention
       (pitch positive = look down, in screen-Y-down world). */
    float cosY = my_cosf(cam.yaw);
    float sinY = my_sinf(cam.yaw);
    float cosP = my_cosf(cam.pitch);
    float sinP = my_sinf(cam.pitch);
    float dirX =  sinY * cosP;
    float dirY =  sinP;
    float dirZ =  cosY * cosP;
    float t;
    int x, y, z;
    int prevX = -999, prevY = -999, prevZ = -999;
    for (t = 0.0f; t < PLAYER_REACH; t += RAY_STEP) {
        x = (int)(cam.pos.x + dirX * t);
        y = (int)(cam.pos.y + dirY * t);
        z = (int)(cam.pos.z + dirZ * t);
        if (x < 0 || x >= WORLD_SX ||
            y < 0 || y >= WORLD_SY ||
            z < 0 || z >= WORLD_SZ) {
            prevX = x; prevY = y; prevZ = z;
            continue;
        }
        if (world[x][y][z] != (uint8)BLOCK_AIR) {
            if (action == 0) {
                world[x][y][z] = (uint8)BLOCK_AIR;
                updateFaceMaskRegion(x, y, z);
            } else if (prevX >= 0 && prevX < WORLD_SX &&
                       prevY >= 0 && prevY < WORLD_SY &&
                       prevZ >= 0 && prevZ < WORLD_SZ) {
                /* Place a DIRT block in the last AIR cell on the ray. */
                world[prevX][prevY][prevZ] = (uint8)BLOCK_DIRT;
                updateFaceMaskRegion(prevX, prevY, prevZ);
            }
            return;
        }
        prevX = x; prevY = y; prevZ = z;
    }
}

int32 mrc_event(int32 ev, int32 p0, int32 p1) {
    if (ev == MR_KEY_PRESS) {
        dx = 0.0f;
        dz = 0.0f;
        if (p0 ==  MR_KEY_UP) {
        dx += my_sinf(cam.yaw) * move_speed;
        dz += my_cosf(cam.yaw) * move_speed;
        }
        if (p0 == MR_KEY_DOWN) {
        dx -= my_sinf(cam.yaw) * move_speed;
        dz -= my_cosf(cam.yaw) * move_speed;
        }
        if (p0 == MR_KEY_LEFT) {
        dx -= my_cosf(cam.yaw) * move_speed;
        dz += my_sinf(cam.yaw) * move_speed;
        }
        if (p0 == MR_KEY_RIGHT) {
        dx += my_cosf(cam.yaw) * move_speed;
        dz -= my_sinf(cam.yaw) * move_speed;
        }
        /* '5' breaks block at look-center, '0' places one in front.
           Both ASCII codes (53, 48) and MR_KEY_NUM5/0 (if defined by
           the SDK on this platform) are accepted. */
        if (p0 == 53) g_action_break = 1;
        if (p0 == 48) g_action_place = 1;
#ifdef MR_KEY_NUM5
        if (p0 == MR_KEY_NUM5) g_action_break = 1;
#endif
#ifdef MR_KEY_NUM0
        if (p0 == MR_KEY_NUM0) g_action_place = 1;
#endif

        cam.pos.x += dx;
        cam.pos.z += dz;
        
    } else if (ev == MR_MOUSE_DOWN) {
        g_curr_tx = p0;
        g_curr_ty = p1;
        diff_x = g_curr_tx - 120;
        diff_y = g_curr_ty - 160;
        
    } else if (ev == MR_MOUSE_UP) {
        diff_x = 0;
        diff_y = 0;
    }
    
    return MR_SUCCESS;
}

uint8 getBlock(int x, int y, int z) {
    if (x < 0 || x >= WORLD_SX) return (uint8)BLOCK_AIR;
    if (y < 0 || y >= WORLD_SY) return (uint8)BLOCK_AIR;
    if (z < 0 || z >= WORLD_SZ) return (uint8)BLOCK_AIR;
    return world[x][y][z];
}

uint8 computeFaceMask(int x, int y, int z) {
    int f;
    uint8 mask;
    if (world[x][y][z] == (uint8)BLOCK_AIR) return 0;
    mask = 0;
    for (f = 0; f < 6; f++) {
        if (getBlock(x + face_dx[f], y + face_dy[f], z + face_dz[f]) == (uint8)BLOCK_AIR) {
            mask = (uint8)(mask | (1 << f));
        }
    }
    return mask;
}

void rebuildAllFaceMasks(void) {
    int x, y, z;
    for (x = 0; x < WORLD_SX; x++) {
        for (y = 0; y < WORLD_SY; y++) {
            for (z = 0; z < WORLD_SZ; z++) {
                visibleFaces[x][y][z] = computeFaceMask(x, y, z);
            }
        }
    }
}

/* Recompute the face mask for (x,y,z) and its 6 axis neighbours.
   Call this after a single block changes (break / place). */
void updateFaceMaskRegion(int x, int y, int z) {
    int f, nx, ny, nz;
    if (x >= 0 && x < WORLD_SX && y >= 0 && y < WORLD_SY && z >= 0 && z < WORLD_SZ) {
        visibleFaces[x][y][z] = computeFaceMask(x, y, z);
    }
    for (f = 0; f < 6; f++) {
        nx = x + face_dx[f];
        ny = y + face_dy[f];
        nz = z + face_dz[f];
        if (nx >= 0 && nx < WORLD_SX && ny >= 0 && ny < WORLD_SY && nz >= 0 && nz < WORLD_SZ) {
            visibleFaces[nx][ny][nz] = computeFaceMask(nx, ny, nz);
        }
    }
}

void gameStart() {
    int x, y, z;
    cam.pos.x = (float)WORLD_SX / 2.0f;
    cam.pos.y = 2.0f;
    cam.pos.z = -2.0f;
    cam.yaw = 0.0f;
    cam.pitch = 0.0f;

    /* projectPoint() maps larger world Y to larger screen Y (i.e. lower
       on screen), so deeper underground sits at higher y indices and the
       camera sits at a low y just above the surface. */
    for (x = 0; x < WORLD_SX; x++) {
        for (y = 0; y < WORLD_SY; y++) {
            for (z = 0; z < WORLD_SZ; z++) {
                if (y == WORLD_SY - 1)                              world[x][y][z] = (uint8)BLOCK_BEDROCK;
                else if (y == WORLD_SY - 2 || y == WORLD_SY - 3)    world[x][y][z] = (uint8)BLOCK_STONE;
                else if (y == WORLD_SY - 4)                         world[x][y][z] = (uint8)BLOCK_DIRT;
                else if (y == WORLD_SY - 5)                         world[x][y][z] = (uint8)BLOCK_GRASS;
                else                                                world[x][y][z] = (uint8)BLOCK_AIR;
            }
        }
    }
}

void fillTriangle(int x0, int y0, int x1, int y1, int x2, int y2, uint8 r, uint8 g, uint8 b) {
    /* Объявление всех переменных в начале метода (C89) */
    int32 minY, maxY, y;
    int32 i, count;
    int32 ex_fp[3];      /* Текущие X координаты ребер в формате Fixed-point (Q16.16) */
    int32 edx_step[3];   /* Шаг изменения X на одну строку Y (Fixed-point) */
    int32 ey_start[3];   /* Начальная координата Y ребра */
    int32 ey_end[3];     /* Конечная координата Y ребра */
    int32 e_active[3];    /* Флаг: является ли ребро активным (не горизонтальным) */
    int32 ix[2];         /* Найденные пересечения X для текущей строки scanline */
    uint8 final_r, final_g, final_b; /* Локальные копии цветов */
    int32 joker;
    int32 temp_dy;
    int32 p0x, p0y, p1x, p1y, p2x, p2y;

    /* Подготовка данных */
    p0x = x0; p0y = y0;
    p1x = x1; p1y = y1;
    p2x = x2; p2y = y2;

    /* 1. Определяем границы отрисовки */
    minY = y0; if (y1 < minY) minY = y1; if (y2 < minY) minY = y2;
    maxY = y0; if (y1 > maxY) maxY = y1; if (y2 > maxY) maxY = y2;

    /* Если треугольник слишком плоский по вертикали, выходим */
    if (minY == maxY) return;

    /* Инициализация переменных ребер */
    for (i = 0; i < 3; i++) {
        e_active[i] = 0;
    }

    /* 2. Настройка трех ребер: (P0-P1), (P1-P2), (P2-P0) */
    /* Ребро 0: P0 -> P1 */
    temp_dy = p1y - p0y;
    if (temp_dy != 0) {
        e_active[0] = 1;
        if (p0y < p1y) {
            ey_start[0] = p0y; ey_end[0] = p1y;
            ex_fp[0] = p0x << 16;
            edx_step[0] = ((p1x - p0x) << 16) / temp_dy;
        } else {
            ey_start[0] = p1y; ey_end[0] = p0y;
            ex_fp[0] = p1x << 16;
            edx_step[0] = ((p0x - p1x) << 16) / (-temp_dy);
        }
    }

    /* Ребро 1: P1 -> P2 */
    temp_dy = p2y - p1y;
    if (temp_dy != 0) {
        e_active[1] = 1;
        if (p1y < p2y) {
            ey_start[1] = p1y; ey_end[1] = p2y;
            ex_fp[1] = p1x << 16;
            edx_step[1] = ((p2x - p1x) << 16) / temp_dy;
        } else {
            ey_start[1] = p2y; ey_end[1] = p1y;
            ex_fp[1] = p2x << 16;
            edx_step[1] = ((p1x - p2x) << 16) / (-temp_dy);
        }
    }

    /* Ребро 2: P2 -> P0 */
    temp_dy = p0y - p2y;
    if (temp_dy != 0) {
        e_active[2] = 1;
        if (p2y < p0y) {
            ey_start[2] = p2y; ey_end[2] = p0y;
            ex_fp[2] = p2x << 16;
            edx_step[2] = ((p0x - p2x) << 16) / temp_dy;
        } else {
            ey_start[2] = p0y; ey_end[2] = p2y;
            ex_fp[2] = p0x << 16;
            edx_step[2] = ((p2x - p0x) << 16) / (-temp_dy);
        }
    }

    /* 3. Основной цикл Scanline Renderer */
    for (y = minY; y <= maxY; y++) {
        count = 0;
        
        /* Ищем пересечения текущей строки Y с активными ребрами */
        for (i = 0; i < 3; i++) {
            if (e_active[i]) {
                /* Используем полуоткрытый интервал [start, end), чтобы избежать двойного учета вершин */
                if (y >= ey_start[i] && y < ey_end[i]) {
                    ix[count++] = ex_fp[i] >> 16; /* Перевод из Fixed-point обратно в int */
                    
                    /* Обновляем X для следующей строки сразу здесь (инкрементально) */
                    ex_fp[i] += edx_step[i];
                }
            }
        }

        /* Если нашли ровно два пересечения — это полноценная горизонтальная линия треугольника */
        if (count == 2) {
            /* Сортируем ix[0] и ix[1], чтобы leftX был меньше rightX */
            if (ix[0] > ix[1]) {
                long temp_x;
                temp_x = ix[0]; ix[0] = ix[1]; ix[1] = temp_x;
            }

            joker = (y % 16);
            final_r = r + joker; final_g = g + joker; final_b = b + joker;

            /* Рисуем линию через API библиотеки */
            mrc_drawLine((int16)ix[0], (int16)y, (int16)ix[1], (int16)y, final_r, final_g, final_b);
        }
    }
}
 
void drawCube(int32 fx, int32 fy, int32 fz, int type, uint8 faceMask,
              fx32 cosY_fx, fx32 sinY_fx, fx32 cosP_fx, fx32 sinP_fx,
              fx32 cam_x_fx, fx32 cam_y_fx, fx32 cam_z_fx) {
    int16 px[8], py[8], pz[8];
    uint8 valid[8];
    fx32  v_x[8], v_y[8], v_z[8];
    fx32  bx, by, bz;
    fx32  half = FX_HALF;
    uint8 r, g, b;
    int i, f;
    int16 v0, v1, v2, v3, sx, sy, sz;
    int32 edge1x, edge1y, edge2x, edge2y, normalZ;
    const int8* face;
    static const int8 faces[6][4] = {
        {0, 3, 2, 1}, {4, 5, 6, 7}, {0, 1, 5, 4},
        {3, 2, 6, 7}, {0, 4, 7, 3}, {1, 2, 6, 5}
    };
    if (type == BLOCK_DIRT) { r = 139; g = 69; b = 19; }
    else if (type == BLOCK_GRASS) { r = 150; g = 210; b = 150; }
    else if (type == BLOCK_STONE) { r = 128; g = 128; b = 128; }
    else if (type == BLOCK_BEDROCK) { r = 64; g = 64; b = 64; }
    else { r = 128; g = 128; b = 128; }

    bx = FX_FROM_INT(fx);
    by = FX_FROM_INT(fy);
    bz = FX_FROM_INT(fz);

    v_x[0] = bx - half; v_y[0] = by - half; v_z[0] = bz - half;
    v_x[1] = bx + half; v_y[1] = by - half; v_z[1] = bz - half;
    v_x[2] = bx + half; v_y[2] = by + half; v_z[2] = bz - half;
    v_x[3] = bx - half; v_y[3] = by + half; v_z[3] = bz - half;
    v_x[4] = bx - half; v_y[4] = by - half; v_z[4] = bz + half;
    v_x[5] = bx + half; v_y[5] = by - half; v_z[5] = bz + half;
    v_x[6] = bx + half; v_y[6] = by + half; v_z[6] = bz + half;
    v_x[7] = bx - half; v_y[7] = by + half; v_z[7] = bz + half;

    for (i = 0; i < 8; i++) {
        if (projectPoint_fx(v_x[i], v_y[i], v_z[i],
                            cam_x_fx, cam_y_fx, cam_z_fx,
                            cosY_fx, sinY_fx, cosP_fx, sinP_fx,
                            &sx, &sy, &sz) == MR_SUCCESS) {
            px[i] = sx; py[i] = sy; pz[i] = sz;
            valid[i] = 1;
        } else {
            px[i] = 0; py[i] = 0; pz[i] = 0;
            valid[i] = 0;
        }
    }

    for (f = 0; f < 6; f++) {
        if (!(faceMask & (1 << f))) continue;
        face = faces[f];
        v0 = face[0];
        v1 = face[1];
        v2 = face[2];
        v3 = face[3];
        /* Skip the face if any of its 4 corners failed the near-plane
           test. Per-face skip is much friendlier than discarding the
           whole cube the moment one corner crosses the camera plane. */
        if (!(valid[v0] & valid[v1] & valid[v2] & valid[v3])) continue;
        edge1x = px[v1] - px[v0];
        edge1y = py[v1] - py[v0];
        edge2x = px[v2] - px[v0];
        edge2y = py[v2] - py[v0];
        normalZ = (edge1x * edge2y) - (edge1y * edge2x);

        if (normalZ > 0) {
            fillTriangle(px[v0], py[v0], px[v1], py[v1], px[v2], py[v2], r, g, b);
            fillTriangle(px[v0], py[v0], px[v2], py[v2], px[v3], py[v3], r, g, b);
            //mrc_drawLine(px[v3], py[v3], px[v0], py[v0], 100, 100, 100);
        }
    }
}

/* Margin (Q16.16, ~2 blocks) behind the camera plane. Whole (x,*,z)
   columns whose yaw-rotated forward distance is past this margin
   contribute nothing to the visible scene, so we skip them before
   projecting any of their vertices. Per-cube vertex culling inside
   projectPoint_fx already drops individual vertices behind near-Z;
   doing the test here at column level avoids 8 fixed-point matrix
   multiplies + a clip per cube in the dropped column. */
#define BEHIND_MARGIN_FX   ((fx32)2 << 16)

void gameDraw(fx32 cosY_fx, fx32 sinY_fx, fx32 cosP_fx, fx32 sinP_fx,
              fx32 cam_x_fx, fx32 cam_y_fx, fx32 cam_z_fx) {
    int x, y, z;
    uint8 type;
    uint8 mask;
    fx32 dx_fx, dz_fx, rotZ_fx;
    for (x = 0; x < WORLD_SX; x++) {
        dx_fx = FX_FROM_INT(x) - cam_x_fx;
        for (z = 0; z < WORLD_SZ; z++) {
            dz_fx = FX_FROM_INT(z) - cam_z_fx;
            /* Yaw-rotated forward distance using the same convention
               as projectPoint_fx so visibility never disagrees with
               the projector. */
            rotZ_fx = -FX_MUL(dx_fx, sinY_fx) + FX_MUL(dz_fx, cosY_fx);
            if (rotZ_fx < -BEHIND_MARGIN_FX) continue;
            for (y = 0; y < WORLD_SY; y++) {
                type = world[x][y][z];
                if (type == BLOCK_AIR) continue;
                mask = visibleFaces[x][y][z];
                if (mask == 0) continue;
                drawCube((int32)x, (int32)y, (int32)z, (int)type, mask,
                         cosY_fx, sinY_fx, cosP_fx, sinP_fx,
                         cam_x_fx, cam_y_fx, cam_z_fx);
            }
        }
    }
}
void mrc_draw(int32 data)
{
    /* Pre-convert per-frame trig and camera position to Q16.16 once,
       so the per-vertex hot path inside drawCube/projectPoint_fx never
       touches software-float operations. */
    fx32 yaw_fx   = FX_FROM_FLOAT(-cam.yaw);
    fx32 pitch_fx = FX_FROM_FLOAT(-cam.pitch);
    fx32 cY_fx = fx_cos(yaw_fx);
    fx32 sY_fx = fx_sin(yaw_fx);
    fx32 cP_fx = fx_cos(pitch_fx);
    fx32 sP_fx = fx_sin(pitch_fx);
    fx32 cam_x_fx = FX_FROM_FLOAT(cam.pos.x);
    fx32 cam_y_fx = FX_FROM_FLOAT(cam.pos.y);
    fx32 cam_z_fx = FX_FROM_FLOAT(cam.pos.z);

    mrc_clearScreen(147, 180, 255);
    cam.yaw   += (float)diff_x * rot_speed;
    cam.pitch -= (float)diff_y * rot_speed;

    /* Per-frame counters & one-shot block actions. */
    g_frame_count++;
    if (g_action_break) { castRayAndAct(0); g_action_break = 0; }
    if (g_action_place) { castRayAndAct(1); g_action_place = 0; }
    gameDraw(cY_fx, sY_fx, cP_fx, sP_fx, cam_x_fx, cam_y_fx, cam_z_fx);
    /* Mario as a perspective-scaled billboard at marioPos.
       Walk-cycle: oscillate +/-MARIO_ANIM_RANGE around base X by sin().
       2.0 world units tall (= 2 blocks). Drawn after the world but
       before HUD so hand/GUI overlay him. */
    {
        float walk = my_sinf((float)g_frame_count * MARIO_ANIM_SPEED) * MARIO_ANIM_RANGE;
        drawSprite3D_fx(&marioBmp,
                        FX_FROM_FLOAT(marioPos.x + walk),
                        FX_FROM_FLOAT(marioPos.y),
                        FX_FROM_FLOAT(marioPos.z),
                        FX_FROM_INT(2),
                        cY_fx, sY_fx, cP_fx, sP_fx,
                        cam_x_fx, cam_y_fx, cam_z_fx);
    }
    gDrawBitmap(&handBmp, SCREEN_WIDTH - handBmp.width, SCREEN_HEIGHT - handBmp.height - 70);
    gDrawBitmapNt(&GUIBmp, SCREEN_WIDTH - GUIBmp.width, SCREEN_HEIGHT - GUIBmp.height);
    /* FPS HUD on top of everything. */
    drawFpsHud();
    mrc_refreshScreen(0,0,SCREEN_WIDTH,SCREEN_HEIGHT);
}
int32 mrc_init(void)
{
    globalTimer = mrc_timerCreate();
    initSinLUT();
    initSpriteData();
    gameStart();
    rebuildAllFaceMasks();
    /* 33 ms tick = 30 frames/sec target. */
    mrc_timerStart(globalTimer, 33, 0, mrc_draw, 1);
	return MR_SUCCESS;
}
/* ===== 1024-entry Q16.16 sine LUT (generated; see gen_sin_LUT.py) ===== */
const int32 fx_sin_lut[1024] = {
          0,        402,        804,       1206,       1608,       2010,       2412,       2814,
       3216,       3617,       4019,       4420,       4821,       5222,       5623,       6023,
       6424,       6824,       7224,       7623,       8022,       8421,       8820,       9218,
       9616,      10014,      10411,      10808,      11204,      11600,      11996,      12391,
      12785,      13180,      13573,      13966,      14359,      14751,      15143,      15534,
      15924,      16314,      16703,      17091,      17479,      17867,      18253,      18639,
      19024,      19409,      19792,      20175,      20557,      20939,      21320,      21699,
      22078,      22457,      22834,      23210,      23586,      23961,      24335,      24708,
      25080,      25451,      25821,      26190,      26558,      26925,      27291,      27656,
      28020,      28383,      28745,      29106,      29466,      29824,      30182,      30538,
      30893,      31248,      31600,      31952,      32303,      32652,      33000,      33347,
      33692,      34037,      34380,      34721,      35062,      35401,      35738,      36075,
      36410,      36744,      37076,      37407,      37736,      38064,      38391,      38716,
      39040,      39362,      39683,      40002,      40320,      40636,      40951,      41264,
      41576,      41886,      42194,      42501,      42806,      43110,      43412,      43713,
      44011,      44308,      44604,      44898,      45190,      45480,      45769,      46056,
      46341,      46624,      46906,      47186,      47464,      47741,      48015,      48288,
      48559,      48828,      49095,      49361,      49624,      49886,      50146,      50404,
      50660,      50914,      51166,      51417,      51665,      51911,      52156,      52398,
      52639,      52878,      53114,      53349,      53581,      53812,      54040,      54267,
      54491,      54714,      54934,      55152,      55368,      55582,      55794,      56004,
      56212,      56418,      56621,      56823,      57022,      57219,      57414,      57607,
      57798,      57986,      58172,      58356,      58538,      58718,      58896,      59071,
      59244,      59415,      59583,      59750,      59914,      60075,      60235,      60392,
      60547,      60700,      60851,      60999,      61145,      61288,      61429,      61568,
      61705,      61839,      61971,      62101,      62228,      62353,      62476,      62596,
      62714,      62830,      62943,      63054,      63162,      63268,      63372,      63473,
      63572,      63668,      63763,      63854,      63944,      64031,      64115,      64197,
      64277,      64354,      64429,      64501,      64571,      64639,      64704,      64766,
      64827,      64884,      64940,      64993,      65043,      65091,      65137,      65180,
      65220,      65259,      65294,      65328,      65358,      65387,      65413,      65436,
      65457,      65476,      65492,      65505,      65516,      65525,      65531,      65535,
      65536,      65535,      65531,      65525,      65516,      65505,      65492,      65476,
      65457,      65436,      65413,      65387,      65358,      65328,      65294,      65259,
      65220,      65180,      65137,      65091,      65043,      64993,      64940,      64884,
      64827,      64766,      64704,      64639,      64571,      64501,      64429,      64354,
      64277,      64197,      64115,      64031,      63944,      63854,      63763,      63668,
      63572,      63473,      63372,      63268,      63162,      63054,      62943,      62830,
      62714,      62596,      62476,      62353,      62228,      62101,      61971,      61839,
      61705,      61568,      61429,      61288,      61145,      60999,      60851,      60700,
      60547,      60392,      60235,      60075,      59914,      59750,      59583,      59415,
      59244,      59071,      58896,      58718,      58538,      58356,      58172,      57986,
      57798,      57607,      57414,      57219,      57022,      56823,      56621,      56418,
      56212,      56004,      55794,      55582,      55368,      55152,      54934,      54714,
      54491,      54267,      54040,      53812,      53581,      53349,      53114,      52878,
      52639,      52398,      52156,      51911,      51665,      51417,      51166,      50914,
      50660,      50404,      50146,      49886,      49624,      49361,      49095,      48828,
      48559,      48288,      48015,      47741,      47464,      47186,      46906,      46624,
      46341,      46056,      45769,      45480,      45190,      44898,      44604,      44308,
      44011,      43713,      43412,      43110,      42806,      42501,      42194,      41886,
      41576,      41264,      40951,      40636,      40320,      40002,      39683,      39362,
      39040,      38716,      38391,      38064,      37736,      37407,      37076,      36744,
      36410,      36075,      35738,      35401,      35062,      34721,      34380,      34037,
      33692,      33347,      33000,      32652,      32303,      31952,      31600,      31248,
      30893,      30538,      30182,      29824,      29466,      29106,      28745,      28383,
      28020,      27656,      27291,      26925,      26558,      26190,      25821,      25451,
      25080,      24708,      24335,      23961,      23586,      23210,      22834,      22457,
      22078,      21699,      21320,      20939,      20557,      20175,      19792,      19409,
      19024,      18639,      18253,      17867,      17479,      17091,      16703,      16314,
      15924,      15534,      15143,      14751,      14359,      13966,      13573,      13180,
      12785,      12391,      11996,      11600,      11204,      10808,      10411,      10014,
       9616,       9218,       8820,       8421,       8022,       7623,       7224,       6824,
       6424,       6023,       5623,       5222,       4821,       4420,       4019,       3617,
       3216,       2814,       2412,       2010,       1608,       1206,        804,        402,
          0,       -402,       -804,      -1206,      -1608,      -2010,      -2412,      -2814,
      -3216,      -3617,      -4019,      -4420,      -4821,      -5222,      -5623,      -6023,
      -6424,      -6824,      -7224,      -7623,      -8022,      -8421,      -8820,      -9218,
      -9616,     -10014,     -10411,     -10808,     -11204,     -11600,     -11996,     -12391,
     -12785,     -13180,     -13573,     -13966,     -14359,     -14751,     -15143,     -15534,
     -15924,     -16314,     -16703,     -17091,     -17479,     -17867,     -18253,     -18639,
     -19024,     -19409,     -19792,     -20175,     -20557,     -20939,     -21320,     -21699,
     -22078,     -22457,     -22834,     -23210,     -23586,     -23961,     -24335,     -24708,
     -25080,     -25451,     -25821,     -26190,     -26558,     -26925,     -27291,     -27656,
     -28020,     -28383,     -28745,     -29106,     -29466,     -29824,     -30182,     -30538,
     -30893,     -31248,     -31600,     -31952,     -32303,     -32652,     -33000,     -33347,
     -33692,     -34037,     -34380,     -34721,     -35062,     -35401,     -35738,     -36075,
     -36410,     -36744,     -37076,     -37407,     -37736,     -38064,     -38391,     -38716,
     -39040,     -39362,     -39683,     -40002,     -40320,     -40636,     -40951,     -41264,
     -41576,     -41886,     -42194,     -42501,     -42806,     -43110,     -43412,     -43713,
     -44011,     -44308,     -44604,     -44898,     -45190,     -45480,     -45769,     -46056,
     -46341,     -46624,     -46906,     -47186,     -47464,     -47741,     -48015,     -48288,
     -48559,     -48828,     -49095,     -49361,     -49624,     -49886,     -50146,     -50404,
     -50660,     -50914,     -51166,     -51417,     -51665,     -51911,     -52156,     -52398,
     -52639,     -52878,     -53114,     -53349,     -53581,     -53812,     -54040,     -54267,
     -54491,     -54714,     -54934,     -55152,     -55368,     -55582,     -55794,     -56004,
     -56212,     -56418,     -56621,     -56823,     -57022,     -57219,     -57414,     -57607,
     -57798,     -57986,     -58172,     -58356,     -58538,     -58718,     -58896,     -59071,
     -59244,     -59415,     -59583,     -59750,     -59914,     -60075,     -60235,     -60392,
     -60547,     -60700,     -60851,     -60999,     -61145,     -61288,     -61429,     -61568,
     -61705,     -61839,     -61971,     -62101,     -62228,     -62353,     -62476,     -62596,
     -62714,     -62830,     -62943,     -63054,     -63162,     -63268,     -63372,     -63473,
     -63572,     -63668,     -63763,     -63854,     -63944,     -64031,     -64115,     -64197,
     -64277,     -64354,     -64429,     -64501,     -64571,     -64639,     -64704,     -64766,
     -64827,     -64884,     -64940,     -64993,     -65043,     -65091,     -65137,     -65180,
     -65220,     -65259,     -65294,     -65328,     -65358,     -65387,     -65413,     -65436,
     -65457,     -65476,     -65492,     -65505,     -65516,     -65525,     -65531,     -65535,
     -65536,     -65535,     -65531,     -65525,     -65516,     -65505,     -65492,     -65476,
     -65457,     -65436,     -65413,     -65387,     -65358,     -65328,     -65294,     -65259,
     -65220,     -65180,     -65137,     -65091,     -65043,     -64993,     -64940,     -64884,
     -64827,     -64766,     -64704,     -64639,     -64571,     -64501,     -64429,     -64354,
     -64277,     -64197,     -64115,     -64031,     -63944,     -63854,     -63763,     -63668,
     -63572,     -63473,     -63372,     -63268,     -63162,     -63054,     -62943,     -62830,
     -62714,     -62596,     -62476,     -62353,     -62228,     -62101,     -61971,     -61839,
     -61705,     -61568,     -61429,     -61288,     -61145,     -60999,     -60851,     -60700,
     -60547,     -60392,     -60235,     -60075,     -59914,     -59750,     -59583,     -59415,
     -59244,     -59071,     -58896,     -58718,     -58538,     -58356,     -58172,     -57986,
     -57798,     -57607,     -57414,     -57219,     -57022,     -56823,     -56621,     -56418,
     -56212,     -56004,     -55794,     -55582,     -55368,     -55152,     -54934,     -54714,
     -54491,     -54267,     -54040,     -53812,     -53581,     -53349,     -53114,     -52878,
     -52639,     -52398,     -52156,     -51911,     -51665,     -51417,     -51166,     -50914,
     -50660,     -50404,     -50146,     -49886,     -49624,     -49361,     -49095,     -48828,
     -48559,     -48288,     -48015,     -47741,     -47464,     -47186,     -46906,     -46624,
     -46341,     -46056,     -45769,     -45480,     -45190,     -44898,     -44604,     -44308,
     -44011,     -43713,     -43412,     -43110,     -42806,     -42501,     -42194,     -41886,
     -41576,     -41264,     -40951,     -40636,     -40320,     -40002,     -39683,     -39362,
     -39040,     -38716,     -38391,     -38064,     -37736,     -37407,     -37076,     -36744,
     -36410,     -36075,     -35738,     -35401,     -35062,     -34721,     -34380,     -34037,
     -33692,     -33347,     -33000,     -32652,     -32303,     -31952,     -31600,     -31248,
     -30893,     -30538,     -30182,     -29824,     -29466,     -29106,     -28745,     -28383,
     -28020,     -27656,     -27291,     -26925,     -26558,     -26190,     -25821,     -25451,
     -25080,     -24708,     -24335,     -23961,     -23586,     -23210,     -22834,     -22457,
     -22078,     -21699,     -21320,     -20939,     -20557,     -20175,     -19792,     -19409,
     -19024,     -18639,     -18253,     -17867,     -17479,     -17091,     -16703,     -16314,
     -15924,     -15534,     -15143,     -14751,     -14359,     -13966,     -13573,     -13180,
     -12785,     -12391,     -11996,     -11600,     -11204,     -10808,     -10411,     -10014,
      -9616,      -9218,      -8820,      -8421,      -8022,      -7623,      -7224,      -6824,
      -6424,      -6023,      -5623,      -5222,      -4821,      -4420,      -4019,      -3617,
      -3216,      -2814,      -2412,      -2010,      -1608,      -1206,       -804,       -402
};
